# -*- coding: utf-8 -*-
"""population.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lPNqz56065FtVKDUahXMQlAp0IhhB6lC
"""

def population_growth(Po, L, M, I, E, method='total'):
    """
    population_growth(Po, L, M, I, E, method) 
    
    The Po, L, M, I, and E arguments are required. 
    If the method argument is empty it will run by default "total"
    
    Po : Population in the initial year of calculation
    L  : Number of births
    M  : Number of deaths
    I  : Number of immigration
    E  : Number of emigration
    
    Parameters:
    -----------
    int    : Po, L, M, I, E
    string : method
    
    Returns:
    Total(int)        : result of Po + (L-M) + (I-E)
    Persentase(float) : result of (((L-M) + (I-E)) / Po) * (100/100)
    
    """
    try:
        method = method.lower()
    except:
        method = str(method)
    
    if method == 'total':
        result = Po + (L-M) + (I-E)
    elif method == 'persentase':
        #persen = 100%
        result = (((L-M) + (I-E)) / Po) * (100/100)
    else:
        result = "This method is not in the module (str)"
    return result